{% set name = "python-cppcolormap" %}
{% set version = "0.2.3" %}
{% set sha256 = "05df1df441d849f8c59915f09f66567bf5cf6cb366d38ee7cb325aa9c4f56b09" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/cppcolormap/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]
  script:
    - python setup.py build
    - python setup.py install

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pyxtensor
  run:
    - python

test:
  imports:
    - cppcolormap

about:
  home: https://github.com/tdegeus/cppcolormap
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: 'Library with colormaps for C++/Python.'
  description: 'Library with colormaps for C++/Python.'
  doc_url: https://github.com/tdegeus/cppcolormap
  dev_url: https://github.com/tdegeus/cppcolormap

extra:
  recipe-maintainers:
    - tdegeus
